### ISSUE TITLE
Metadata and tags cleanup

### ISSUE THREAD

**Issue by apalumbo** [KyleRoss/node-lambda-log#13]
First of all thank you for your work.

I was about to use lambda-log in our project and did't have time to jump in its code so sorry if this is a dumb question.
In all the example it is suggested to set some logging info in the log instance (metadata, tags) so that they can be logged later in all the invocations. I was just wondering if it could be needed to cleanup that informations (like in a try / finally). I was wondering about that as I undestood that log is used as a singleton. Is the handler the only safe point to push that extra info ?

**Comment by KyleRoss** [comment]
@apalumbo There is a few different ways the metadata and tags work within this module. If you are using the default singleton that is exported by default, you set the metadata and tags via configuration properties. These properties will stay for the life of the process, no matter where you require the module in. This is known as global metadata and tags. If you wanted to add a tag to all logs that contains your process version or environment, this would be the way to do it.

If you wanted to include metadata or tags for a specific file, you could create a new instance of `LambdaLog` for each file and set the metadata and tags for that instance. For example:

```js
// myModule.js
const { LambdaLog } = require('lambda-log');
const log = new LambdaLog({
    tags: ['myModule']
});
```

With this, all logs in this file will be tagged with `myModule` automatically, but requiring in lambda-log anywhere else will not include this tag as you have created a new instance.

If you wanted to include metadata or tags for functionality, you may do so as the second and third arguments for any of the logging functions. For example:

```js
log.info('This is a test', { abc: 123 }, ['myFunction']);
```


If you really want to be able to cleanup any metadata and tags from the global instance (singleton), you can do so at any time by manipulating the configuration object. For example:

```js
const log = require('lambda-log');

// Set some global tags
log.options.tags = ['myModule'];

// ... do stuff ...

// Remove global tags
log.options.tags = [];
```

While that is possible to do, I'd suggest against it and would recommend using new instances per file or by passing this information in via the logging functions. Either way, `log.options` can be changed at any time to do what you need it to do 😄 

Let me know if you have any additional questions!
