### ISSUE TITLE
Removing the default prefix on each log row

### ISSUE THREAD

**Issue by schwamster** [KyleRoss/node-lambda-log#2]
thanks for the npm packages it is quite handy! One thing i am wondering about is the annoying default prefixes that aws automatically adds in the beginning of each log row:

![image](https://user-images.githubusercontent.com/10597594/38566417-e67f2a60-3ce3-11e8-80da-6beedd04bb80.png)

I know this has nothing to do with your code, but i just wanted to know if you maybe found a way to remove that?

**Comment by KyleRoss** [comment]
@schwamster That has been an annoyance to me also, but unfortunately it's something that CloudWatch Logs enforces and I have yet figured out a way around it. Might be something good to feature request to AWS.

**Comment by sonphnt** [comment]
@schwamster @KyleRoss I have the same issue with that unnecessary information because AWS already have a timestamp. Do we have a workaround way?
