### ISSUE TITLE
Setting Debug Option results in "Info" logs in AWS CloudWatch

### ISSUE THREAD

**Issue by jogura** [KyleRoss/node-lambda-log#21]
Using the code in a simple node file, setting debug true/false gives expected results.

  // Enable debug messages
  log.options.debug = true;
  log.debug('some debug message again');

However the result "Log" type in AWS CloudWatch Is: 
```
2019-09-03T17:41:29.607Z 30b96d89-14ec-489a-bf47-2b4df94b1723	INFO some debug message again
```

The expected result is: 
```
2019-09-03T17:41:29.607Z 30b96d89-14ec-489a-bf47-2b4df94b1723	DEBUG some debug message again
```

I think the error is on line: https://github.com/KyleRoss/node-lambda-log/blob/master/lib/LambdaLog.js#L76
the code should be changed from: 
     `if(this.options.debug) return 'log';` 
to: 
     `if(this.options.debug) return 'debug';

**Comment by KyleRoss** [comment]
Thanks for reporting, the change has been made and published to NPM as version 2.3.1.

**Comment by KyleRoss** [comment]
@all-contributors please add @jogold for bug

**Comment by sonphnt** [comment]
@KyleRoss is it possible to remove the default timestramp, uuid, loglevel out of the message? the bold highlight should be removed because in CloudWatch log we already have Timestamp column
`**2019-09-03T17:41:29.607Z 30b96d89-14ec-489a-bf47-2b4df94b1723	INFO** some debug message again`
