### ISSUE TITLE
log.options.meta is of type any - Unsafe member access .event on an any value.

### ISSUE THREAD

**Issue by akleiber** [KyleRoss/node-lambda-log#28]
If using recommended rules the rule [no-unsafe-member-access](https://github.com/typescript-eslint/typescript-eslint/blob/v3.4.0/packages/eslint-plugin/docs/rules/no-unsafe-member-access.md) will disallow accessing `log.options.meta` because it is typed as `any`.

Would it be okay to type `log.options.meta` as `Record<string, unknown>` @KyleRoss ?

**Comment by KyleRoss** [comment]
@akleiber Yes, that should work. Is this due to the typings?

**Comment by akleiber** [comment]
Sorry for the delay :) Yes due to the typings - the types for lambda-log are managed via DefinitelyTyped right? So I guess I need to open a PR at https://github.com/DefinitelyTyped/DefinitelyTyped/pulls

**Comment by KyleRoss** [comment]
@akleiber That is correct, please feel free to open a PR there to get those fixed :) Let me know if you have any issues.
