### ISSUE TITLE
_logLevel and log tag seems repetitive

### ISSUE THREAD

**Issue by tulsidas** [KyleRoss/node-lambda-log#29]
On all the logs there is both _logLevel and the log tag, that seems repetitive in the sense that I'm having the same info twice (thrice, considering that AWS CloudWatch also adds the level), can this be customized to remove the log tag for example? I saw that it is hardcoded on the source code

{"_logLevel":"info","msg":"hiya","_tags":["log","info"]}

**Comment by KyleRoss** [comment]
@tulsidas I agree that it is repetitive and was added originally to allow for different methods of querying logs within CloudWatch. I will think through some options to make these default tags optional or overridable.

**Comment by KyleRoss** [comment]
@tulsidas This has been implemented and published in v3.0.0. I'm still waiting for the new documentation site to go live with the details.

In short, the default tags `["log", "LEVEL"]` have been removed. In addition, you now have the ability to remove the `_logLevel` field from the message JSON as well.

Thanks for the idea!

**Comment by KyleRoss** [comment]
@all-contributors please add @tulsidas for ideas

**Comment by tulsidas** [comment]
yaaaaay! 💪
