### ISSUE TITLE
New website link not working

### ISSUE THREAD

**Issue by rcoundon** [KyleRoss/node-lambda-log#35]
## What happens?
Accessing link in docs to new website redirects to https://js.org/?lambdalog and no content

### What were you expecting to happen?
To see the new website :-D

**Comment by KyleRoss** [comment]
@rcoundon Thanks for reporting, I'm currently waiting for `lambdalog.js.org` to be merged (https://github.com/js-org/js.org/pull/5804) before the site will be online. Let's hope it is sometime this morning :)

I'll leave this open until it's complete.

**Comment by rcoundon** [comment]
No worries - the main thing is you're aware of it 👍

**Comment by KyleRoss** [comment]
@rcoundon Site is now live! https://lambdalog.js.org
