### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by KyleRoss** [KyleRoss/node-lambda-log#7]
# Version 2.0.0
Complete refactor of lambda-log to allow better extensibility and a handful of new features. This issue is to keep track of the proposed changes. During development, changes will be committed to the `2.0.0` branch.

**Note:** Any completed tasks below are shown as completed development/implementation, it does not mean it has been committed yet.

### Module/Organization
- [x] Move functionality out of `index.js`.

### Internals
- [x] Utilize `console` module to create custom instance of `console`.
- [x] Allow configuring class via constructor (#3) 

### Configuration
- [x] **Breaking:** Rename `LambdaLog.config` to `LambdaLog.options`.
- [x] Add configuration for `stdoutStream` and `stderrStream` for custom console implementations.
- [x] Add configuration option that allows appending dynamic metadata to each log.
- [x] Add configuration option for `JSON.stringify` replacer function.

### Features
- [x] Add ability to configure log levels.
- [x] Add ability to add tags to individual logs.

### Log Message Class (New)
- [x] Make each generated log message its own class with custom methods.
- [x] Move `isError` function to this class.
- [x] Implement dynamic metadata functionality.
- [x] Implement JSON replacer functionality.
- [x] Add `toJSON()` utility function.
- [x] Add getters for the object value of the message log.
- [x] Add `throw` getter to message to allow throwing of errors by chaining (ex. `log.error(err).throw;`).

### Fixes
- [x] Handle meta data that is not in object format passed into logs by wrapping it in an object.

### Tests
- [x] Update tests for changed functionality.
- [x] Add tests for new functionality.

### Documentation
- [x] Add JSDoc comments to new code.
- [x] Update documentation in README.
- [x] Update CHANGELOG with all changes.
- [x] Add migration guide for v1 to v2.

**Comment by KyleRoss** [comment]
Version 2.0.0 has been published to npm

**Comment by armonge** [comment]
any plans to support typescript ?
