### ISSUE TITLE
lambda_log_default.a is not a constructor

### ISSUE THREAD

**Issue by quickdraw6906** [KyleRoss/node-lambda-log#79]
## What happens?

undefined ERROR Uncaught Exception {"errorType":"TypeError","errorMessage":"lambda_log_default.a is not a constructor"

## Steps to reproduce

/lib/logging.ts:
import LambdaLog from "lambda-log";
export const logger: LambdaLog = new LambdaLog();

/util/logging.ts:
import { logger } from "../libs/logging";

/src/somefile.ts:
import * as logger from "../util/logging";
logger.info('something');

## Any logs, output, examples?

undefined ERROR Uncaught Exception {"errorType":"TypeError","errorMessage":"lambda_log_default.a is not a constructor","stack":["TypeError: lambda_log_default.a is not a constructor"," at Module.<anonymous> (/var/task/src/psi_service_products/webpack:/home/ubuntu/workspace/ods-lambda-deploy/ods_lambda/etl/src/libs/logging.ts:10:34)"," at __webpack_require__ (/var/task/src/psi_service_products/webpack:/webpack/bootstrap:19:1)"," at /var/task/src/psi_service_products/webpack:/webpack/bootstrap:83:1"," at Object.<anonymous> (/var/task/src/psi_service_products/psiServiceProducts.js:87:10)"," at Module._compile (internal/modules/cjs/loader.js:1085:14)"," at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)"," at Module.load (internal/modules/cjs/loader.js:950:32)"," at Function.Module._load (internal/modules/cjs/loader.js:790:12)"," at Module.require (internal/modules/cjs/loader.js:974:19)"," at require (internal/modules/cjs/helpers.js:93:18)"]}

## Environment

**Operating System:** 
AWS Lambda

**Node Version:** 
Node.js 14.x

**Comment by KyleRoss** [comment]
@quickdraw6906 You are missing the curly braces:

```js
import { LambdaLog } from "lambda-log";
export const logger: LambdaLog = new LambdaLog();
```
